# Full CI matrix on all pushes to master branch, and all PRs
name: Java CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11, 17, 21, 24]
        # macos-13 is x86, macos-latest is aarch64
        os: [ubuntu-latest, macos-13, macos-latest]
        include:
          - java: 17
            os: 'ubuntu-24.04-arm'
      # Run all tests even if one fails
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Linux requirements
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -yq --allow-downgrades zip unzip libtool automake libltdl-dev texinfo ant ant-optional debhelper-compat default-jdk javahelper libasm-java libffi-dev libx11-dev libxt-dev maven-repo-helper pkg-config
      - name: macOS requirements
        if: contains(matrix.os, 'macos')
        run: |
          brew update
          brew install automake --force
          brew install libtool --force
          brew install texinfo --force
      - name: Checkstyle
        if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '8')
        run: |
          ant checkstyle
          ant dist
      - name: Build with Ant
        run: |
          ant test
          ant test-platform
